spring:
  data:
    redis:
      host: redis
      port: 6379
  datasource:
    url: jdbc:postgresql://db:5432/tasklist_dev
    username: dev_user
    password: dev_password
  thymeleaf:
    cache: false
  liquibase:
    enabled: true
  jpa:
    generate-ddl: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: task-list-group
  security:
    oauth2:
      client:
        provider:
          tasklist-keycloak:
            issuer-uri: http://host.docker.internal:8080/realms/tasklist-keycloak
        registration:
          keycloak:
            provider: tasklist-keycloak
            authorization-grant-type: authorization_code
            client-id: tasklist-keycloak-confidential
            client-secret: 6qT92pg69IelZSSGNMuOOCWPB5oFpV1u
            scope: openid
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
server:
  port: 8083
  error:
    include-stacktrace: always
    include-exception: true
    include-message: always

logging:
  level:
    root: ERROR

springdoc:
  api-docs:
    path: /custom-api-docs
  swagger-ui:
    path: /custom-swagger-ui
repository:
  type: jpa
app:
  jwt:
    secret: "taskSecretKey"
    tokenExpiration: 3m
    refreshTokenExpiration: 30m
  auth-type: keycloak